site_name: Icewind Dale
site_url: https://lbeukennoot.github.io/dnd-icewind-dale/
repo_url: https://github.com/LBeukennoot/dnd-icewind-dale
repo_name: LBeukennoot/dnd-icewind-dale

nav:
  - Home: index.md
  - Sessions: 
    - Session 1: Sessions/Session 1
    - Session 2: Sessions/Session 2
    - Session 3: Sessions/Session 3
    - Session 4: Sessions/Session 4
    - Session 5: Sessions/Session 5
    - Session 6: Sessions/Session 6
    - Session 7: Sessions/Session 7

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    include_sidebar: true

    features:
      - navigation.path

# Extensions
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - backlinks_section:
      add_to_toc: false
      hide_if_empty: true
      title: "Links mentioned"
      description: ""
      description_no_links: "No links."
  - search
  - roamlinks
  - blog
  - rss:
      match_path: sessions/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
